### ISSUE TITLE
About the API

### ISSUE THREAD

**Issue by coderfox** [dev-techmoe/YOSORO-Homepage#1]
I think `add` is not a idempotent action, thus it should be a `POST` instead of `GET`.

**Comment by dev-techmoe** [comment]
这个api其实重点是需要考虑的问题是减少add或者get时的数据量以增强用户体验避免延时感（这也是调用add之后没有response body的原因），调用`get`时也没有任何实际参数提交到后端（可能有的时候F12时你会发现有一个名为`t`带时间戳的参数，但那个实际上用来防cdn缓存的，并没有实际作用），所以`get`和`post`真的无所谓。。

**Comment by coderfox** [comment]
明天沈阳有个我组织的科技活动，来吗？

**Comment by dev-techmoe** [comment]
我前几天刚跑去市里逛了动漫电玩博览会（展览馆的漫展）。。再加之我们这里快开学了还有功课没有做（准高三党哭瞎）。。所以最近实在是没机会再跑市里去了。。抱歉。。。  
不过相信以后总会有机会的 :)
